services:

  backend:

    build:
      context: ../apps/backend

    ports:
      - "8000:8000"

    volumes:
      - ../data:/app/data



  frontend:

      build:
        context: ../apps/frontend
        dockerfile: Dockerfile
        args:
          - VITE_API_URL=${VITE_API_URL}

      env_file:
        - ../apps/frontend/.env

      ports:
        - "3000:4173"  

      depends_on:
        - backend

      restart: always